[package]
name = "ds-catalog-browser-ui"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Minimal read-only Yew UI for browsing offers from a DSP Catalog Broker federated catalog"
repository = "https://github.com/ds-labs-org/ds-catalog-browser-ui"
keywords = ["dataspace", "http"]
categories = []
readme = "README.md"

[dependencies]
console_error_panic_hook = "0.1"
edc-federated-catalog-client = "0.2.5"
patternfly-yew = { version = "0.8", features = ["experimental"] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
web-sys = { version = "0.3", features = ["Window", "Location"] }
yew = { version = "0.23", features = ["csr"] }

[dev-dependencies]
serde_json = "1"
